### ISSUE TITLE
Performance problem: blocking issue

### ISSUE THREAD

**Issue by robmarkcole** [robmarkcole/deepstack-python#1]
As reported on the deepstack slack, I'm having a serious issue with RAM usage and inference time. Typically processing an image is taking ~ 20 seconds, and almost 4 GB RAM is being used by Docker in the process. Im on a MacBook Pro 2017, with 8 GB 2133 MHz LPDDR3, macOS 10.14.2.

![image](https://user-images.githubusercontent.com/11855322/51588106-05790880-1edb-11e9-9cd4-4f239f99f024.png)

**Comment by johnolafenwa** [comment]
Hi @robmarkcole , Thanks for providing more details on your system specs. We have observed this issue when running deepstack on docker toolbox in windows, i assume you are running docker toolbox on macos. 
At present, we primarily support running deepstack on linux machines and on windows 10 pro or docker on macos without using the toolbox.

**Comment by robmarkcole** [comment]
To do: update docs highlighting windows/mac limitations

**Comment by robmarkcole** [comment]
@johnolafenwa I am not running docker toolbox (legacy) but desktop:

![image](https://user-images.githubusercontent.com/11855322/51634159-7526dc00-1f4b-11e9-8fe4-9b9b53723aba.png)

**Comment by johnolafenwa** [comment]
@robmarkcole Thanks for the info. We have not tested DeepStack on MacOS before. We shall look into this. The native non-docker version will also be developed to address the discrepancies in performance caused by docker on windows and mac.

**Comment by robmarkcole** [comment]
This is resolved now

**Comment by OlafenwaMoses** [comment]
Good to know. Thanks @robmarkcole
