### ISSUE TITLE
Compatibilty issue with tensorflow-lite-rest-server

### ISSUE THREAD

**Issue by bestlibre** [robmarkcole/deepstack-python#24]
As stated in [this issue](https://github.com/robmarkcole/tensorflow-lite-rest-server/issues/26) the deepstack-python binding is not compatible with the tensorflow-lite-rest-server.

The mimetype should be send with the image.

**Comment by robmarkcole** [comment]
We should make the tensorflow-lite-rest-server compatible with deepstack, not the other way around. Keeping as issue on tensorflow-lite-rest-server
